### PR TITLE
Crypto changes

### PR DESCRIPTION
**Pull request by Michael-Stanford**

### CODE REVIEW

**Comment by Michael-Stanford** [comment]
This is because Alex Allain was concerned about the cryptographic strength of the uuid module. I changed it to use the built-in Node uuid generator which claims to be cryptographically strong.

**Comment by Rapol** [comment]
It seems that you branched off from Steve aging feature branch. There is some code regarding to the aging grant feature that is no longer needed. You will need to merge with develop again to get rid of these changes or create a branch from develop again or only include the crypto changes.

**Comment by Rapol** [comment]
Also, the authentication code was copied from care-reporter. Have we check if other projects have migrated to use crypto instead of uuid/v4?

**Comment by Michael-Stanford** [comment]
Deleting and re-pushing the crypto-changes branch

**Pull request closed without merging**
